before_commands:
    - "composer install --dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["admin", "asset", "build", "data", "docs", "tests", "vendor", "view"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["admin", "asset", "build", "data", "docs", "tests", "vendor", "view"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["admin", "asset", "build", "data", "docs", "tests", "vendor", "view"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*", "config/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*", "tests/*", "config/*"]
    sensiolabs_security_checker: true
