language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source
  - cd admin
  - npm install -g bower grunt-cli
  - bower install
  - npm install grunt-cli
  - cd ..

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Performance
  - ./vendor/bin/phpcs --standard=PSR2 src test
  - cd admin && grunt test
